Parameters:
  
  MainVPC:
    Type: String
  ImportedKeyPair:
    Type: String
  PrivateInstanceSecurityGroup:
    Type: String
  WebServerSecurityGroup:
    Type: String
  DBUsernameParameter:
    Type: String
  DBPasswordParameter:
    Type: String
  DatabaseEndpoint:
    Type: String

Resources:
  EC2InstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowSSMParameterAccess
      Roles:
        - ec2properrole # Replace with the name of your IAM role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowReadDBSecretsFromSSM
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource:
              - !Sub arn:aws:ssm:us-east-1:013001369500:parameter/${DBUsernameParameter}
              - !Sub arn:aws:ssm:us-east-1:013001369500:parameter/${DBPasswordParameter}
    DependsOn:
      - EC2Role
  
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ec2properrole 
      AssumeRolePolicyDocument: 
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com

      Description: Basic ec2

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore  # Required for SSM agent
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy    # Optional for monitoring

  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  LaunchTemplateEc2Micro:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: ami-052064a798f08f0d3
        InstanceType: t3.micro
        KeyName: !Ref ImportedKeyPair
        IamInstanceProfile: 
          Arn: !GetAtt Ec2InstanceProfile.Arn

        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
          - !Ref PrivateInstanceSecurityGroup  # Add this to allow SSH from bastion hosts

        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash

              yum update -y
              yum install -y awscli mariadb105 httpd unzip git

            
              DB_USER=${DBUsernameParameter}
              DB_PASS="${DBPasswordParameter}"

              echo "Using DB_USER=$DB_USER" >> /var/log/init.log 
              #port 3000
              DB_USER=$(aws ssm get-parameter --name ${DBUsernameParameter} --with-decryption --query "Parameter.Value" --output text --region us-east-1)
              DB_PASS=$(aws ssm get-parameter --name ${DBPasswordParameter} --with-decryption --query "Parameter.Value" --output text --region us-east-1)
              DB_ENDPOINT="${DatabaseEndpoint}";

              sudo yum install docker -y

              sudo systemctl start docker
              sudo systemctl enable docker

              sudo usermod -a -G docker ec2-user

              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose

              git clone https://github.com/danielarell/speedcola.git

              git clone https://github.com/danielarell/Frontend_SpeedCola /var/www/html/
              echo '<!DOCTYPE html><html><head><title>Health Check</title></head><body>OK</body></html>' > /var/www/html/health.html
              echo "DB_USER=$DB_USER\nDB_HOST=$DB_ENDPOINT\nDB_PASSWORD=$DB_PASS" > /var/www/html/.env
              echo "CREATE DATABASE facturas;" |  mysql -h $DB_ENDPOINT -u "$DB_USER" -p"$DB_PASS" ;

              #docker-compose up -d --build


              chown -R apache:apache /var/www/html/
              chmod -R 755 /var/www/html/

              systemctl restart httpd
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: environment
            Value: development
        - ResourceType: volume
          Tags:
          - Key: environment
            Value: development



Outputs:
  LaunchTemplateEc2Micro:
    Value: !Ref LaunchTemplateEc2Micro

  LatestTemplateVersion:
    Value: !GetAtt LaunchTemplateEc2Micro.LatestVersionNumber
