Parameters:
  
  MainVPC:
    Type: String
  ImportedKeyPair:
    Type: String
  InstanceProfileArn:
    Type: String
  PrivateInstanceSecurityGroup:
    Type: String
  WebServerSecurityGroup:
    Type: String
  DBUsernameParameter:
    Type: String
  DBPasswordParameter:
    Type: String
  DatabaseEndpoint:
    Type: String

Resources:

  LaunchTemplateEc2Micro:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: ami-014dcf9390a1891fe
        InstanceType: t3.micro
        KeyName: !Ref ImportedKeyPair
        IamInstanceProfile: 
          Arn: !Ref InstanceProfileArn

        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
          - !Ref PrivateInstanceSecurityGroup  # Add this to allow SSH from bastion hosts

        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y awscli jq mariadb105 php httpd php-mysqli unzip git

              systemctl start httpd
              systemctl enable httpd

              DB_USER=${DBUsernameParameter}
              echo "Using DB_USER=$DB_USER" >> /var/log/init.log 
              DB_PASS="${DBPasswordParameter}"
              DB_ENDPOINT="${DatabaseEndpoint}";
              #port 3000
              
              git clone https://github.com/danielarell/Frontend_SpeedCola /var/www/html/
              echo  "-h" $DB_ENDPOINT "-u" "$DB_USER" "-p" "$DB_PASS" ;
              sed -i "s/DB_USER=admin/DB_USER=$DB_USER/g" ~/.env
              sed -i "s/DB_HOST=.*/DB_HOST=$DB_HOST/g" ~/.env
              sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$DB_PASS/g" ~/.env

              chown -R apache:apache /var/www/html/
              chmod -R 755 /var/www/html/

              systemctl restart httpd
        TagSpecifications:
        - ResourceType: instance
          Tags:
          - Key: environment
            Value: development
        - ResourceType: volume
          Tags:
          - Key: environment
            Value: development



Outputs:
  LaunchTemplateEc2Micro:
    Value: !Ref LaunchTemplateEc2Micro
