
Parameters:
  FirstPublicSubnet:
  SecondPublicSubnet:
  ALBSecurityGroup:
  c2LaunchTemplate:

Resources:

  IncomingTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: incoming-target-group
      Port: 80
      Protocol: HTTP
      VpcId: !Ref MainVPC
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPath: /health.html  # 
      HealthCheckIntervalSeconds: 30  #
      HealthCheckTimeoutSeconds: 5   #
      HealthyThresholdCount: 2       #
      UnhealthyThresholdCount: 2     #
      Matcher:
        HttpCode: 200

  

  # Bastion Host in Public Subnet A (AZ1)
  IncomingTrafficLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: IncomingTrafficLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup  # AQUÍ: Añadir referencia al Security Group nuevo
      Subnets: 
        - !Ref FirstPublicSubnet
        - !Ref SecondPublicSubnet
      Type: application


#----- AutoScaling policy
  TargetTrackingASP:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: PercentChangeInCapacity
      AutoScalingGroupName: !Ref WebServerASG
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration: 
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join 
            - '/' 
            - - !GetAtt IncomingTrafficLoadBalancer.LoadBalancerFullName
              - !GetAtt IncomingTargetGroup.TargetGroupFullName
        TargetValue: 1000
            


#--------------------------------------Auto Scaling Group-------------------------------
  WebServerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: LaunchTemplateEc2Micro
    Properties:
      AutoScalingGroupName: !Sub ${AWS::StackName}-ASG
      AvailabilityZones: 
        - "us-east-1a"
        - "us-east-1b"
      DefaultInstanceWarmup: 0
      DesiredCapacity: 1
      #DesiredCapacityType: vcpu
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplateEc2Micro
        Version: !GetAtt LaunchTemplateEc2Micro.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      NewInstancesProtectedFromScaleIn: false
      #PlacementGroup: String
      #ServiceLinkedRoleARN: String
      #Tags: 
        #- TagProperty
      TargetGroupARNs: 
        - !Ref IncomingTargetGroup
      VPCZoneIdentifier:
      - !Ref FirstPrivateSubnet
      - !Ref SecondPrivateSubnet
