
Parameters:
  MainVPC:
    Type: String

  FirstPublicSubnet:
    Type: String
  FirstPrivateSubnet:
    Type: String
  SecondPrivateSubnet:
    Type: String
  ALBSecurityGroup:
    Type: String
  LaunchTemplateEc2Micro:
    Type: String

Resources:


  # Bastion Host in Public Subnet A (AZ1)
  IncomingTrafficLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: IncomingTrafficLoadBalancer
      SecurityGroups:
        - !Ref ALBSecurityGroup  # AQUÍ: Añadir referencia al Security Group nuevo
      Subnets: 
        - !Ref FirstPublicSubnet
      Type: application


#----- AutoScaling policy
  TargetTrackingASP:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: PercentChangeInCapacity
      AutoScalingGroupName: !Ref WebServerASG
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration: 
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join 
            - '/' 
            - - !GetAtt IncomingTrafficLoadBalancer.LoadBalancerFullName
              - !GetAtt IncomingTargetGroup.TargetGroupFullName
        TargetValue: 1000
            


