
Resources:

  ImportedKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: "public_key"  # Nombre del key pair en AWS
      PublicKeyMaterial: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLy2dHptMDN94jchLc3Nr1HFLlNxmlenk+/fotuUvr/RQ/XZG3RmOSLiJZD0a/Xn+rirFgxT/Hy3Qhv2KfR1VYkIGB6IJhoWE+fTi92yZlUOln4E9fPl5tLWHRuTrDwPf8FoFciyJ0+JJpu0qzK+1EEzs+YKRMM1gnM+yihVnnIV3A5ymfp73ysPmwJf7Tsyx30QpkY2Fgck6XLj39X/69MYWIWldYEv3oS+ZtpHXwt6GljoQDb6snGiUbjP7Ib2FcLME5Yjy16kgv0G4ok0tMR81QkOTp8lgexOullQIvpu8BhJODyf8SESOLMmX5t4Xd9KD9vliuinXshgxwkPbR"
      Tags:
        - Key: Name
          Value: "public_key"

  
  DBSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: !Sub ${AWS::StackName}-db-credentials
        GenerateSecretString:
          SecretStringTemplate: '{"username": "admin"}'
          GenerateStringKey: "password"
          PasswordLength: 16
          ExcludeCharacters: '"@/\'

  DBUsernameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DBSecret
    Properties:
      Name: "/myapp/db/username"
      Type: String
      Value: !Sub "{{resolve:secretsmanager:${DBSecret}::username}}"

  DBPasswordParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DBSecret
    Properties:
      Name: "/myapp/db/password"
      Type: String
      Value: !Sub "{{resolve:secretsmanager:${DBSecret}::password}}"

  MyDatabaseSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable MySQL access
        VpcId: !Ref MainVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 3306
            ToPort: 3306
            CidrIp: 10.0.0.0/16
        Tags:
          - Key: Name
            Value: !Ref BastionSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subredes privadas para la base de datos"
      SubnetIds:
        - !Ref SecondPrivateSubnet #subnet B
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-subnet-group

  MyDatabase:
    Type: AWS::RDS::DBInstance
    DependsOn: 
      - MyDatabaseSecurityGroup
      - DBSecret
    DeletionPolicy: 'Delete'
    UpdateReplacePolicy: 'Delete'
    Properties:
      DBInstanceIdentifier: countries
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}::password}}'
      VPCSecurityGroups:
        - !Ref MyDatabaseSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      MultiAZ: true # Alta disponibilidad en múltiples AZ
