
Resources:

  ImportedKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: "public_key"  # Nombre del key pair en AWS
      PublicKeyMaterial: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLy2dHptMDN94jchLc3Nr1HFLlNxmlenk+/fotuUvr/RQ/XZG3RmOSLiJZD0a/Xn+rirFgxT/Hy3Qhv2KfR1VYkIGB6IJhoWE+fTi92yZlUOln4E9fPl5tLWHRuTrDwPf8FoFciyJ0+JJpu0qzK+1EEzs+YKRMM1gnM+yihVnnIV3A5ymfp73ysPmwJf7Tsyx30QpkY2Fgck6XLj39X/69MYWIWldYEv3oS+ZtpHXwt6GljoQDb6snGiUbjP7Ib2FcLME5Yjy16kgv0G4ok0tMR81QkOTp8lgexOullQIvpu8BhJODyf8SESOLMmX5t4Xd9KD9vliuinXshgxwkPbR"
      Tags:
        - Key: Name
          Value: "public_key"

  
  DBSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: !Sub ${AWS::StackName}-db-credentials
        GenerateSecretString:
          SecretStringTemplate: '{"username": "admin"}'
          GenerateStringKey: "password"
          PasswordLength: 16
          ExcludeCharacters: '"@/\!'

  DBUsernameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DBSecret
    Properties:
      Name: "/myapp/db/username"
      Type: String
      Value: !Sub "{{resolve:secretsmanager:${DBSecret}::username}}"

  DBPasswordParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DBSecret
    Properties:
      Name: "/myapp/db/password"
      Type: String
      Value: !Sub "{{resolve:secretsmanager:${DBSecret}::password}}"

Outputs:
  DBSecret:
    Value: !Ref DBSecret

  DBPasswordParameter:
    Value: !Ref DBPasswordParameter

  ImportedKeyPair:
    Value: !Ref ImportedKeyPair
