
Parameters:
  
  S3Url:
    Description: Link with Repo
    Type: String
  PublicKey:
    Description: Secret PublicKey
    Type: String

  

Resources:

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/LambdaStarter.yaml"


  WebSocketApi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/WebSocket.yaml"



  SocketIntegrations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/SocketIntegrations.yaml"
      Parameters:
        SocketApi:
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]

        DefaultLambda:
          Fn::GetAtt: [LambdaStack,Outputs.DefaultLambda]
        ConnectLambda:
          Fn::GetAtt: [LambdaStack,Outputs.ConnectLambda]
        DisconnectLambda:
          Fn::GetAtt: [LambdaStack,Outputs.DisconnectLambda]
        SendMessageLambda:
          Fn::GetAtt: [LambdaStack,Outputs.SendMessageLambda]

    DependsOn:
      - WebSocketApi
      - LambdaStack

  SocketRoutes:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/SocketRoutes.yaml"
      Parameters:
        SocketApi:
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]
        DefaultIntegration:
          Fn::GetAtt: [SocketIntegrations,Outputs.DefaultIntegration]
        ConnectIntegration:
          Fn::GetAtt: [SocketIntegrations,Outputs.ConnectIntegration]
        DisconnectIntegration:
          Fn::GetAtt: [SocketIntegrations,Outputs.DisconnectIntegration]
        SendMessageIntegration:
          Fn::GetAtt: [SocketIntegrations,Outputs.SendMessageIntegration]

  Deployment:
    DependsOn: SocketRoutes
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: 
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev
      Description: dev stage
      DeploymentId: 
        !Ref Deployment
      ApiId: 
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]

Outputs:
  ConnectionURL:
    Value: !Sub wss://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev



