
Parameters:
  
  S3Url:
    Description: Link with Repo
    Type: String
  PublicKey:
    Description: Secret PublicKey
    Type: String

  

Resources:

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/LambdaStarter.yaml"


  WebSocketApi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/WebSocket.yaml"



  SocketIntegrations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/SocketIntegrations.yaml"
      Parameters:
        SocketApi:
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]
        ConnectLambda:
            Fn::GetAtt: [LambdaStack, Outputs.ConnectLambda]

    DependsOn:
      - WebSocketApi
      - LambdaStack

  SocketRoutes:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${S3Url}/cloudformation/chat/SocketRoutes.yaml"
      Parameters:
        SocketApi:
          Fn::GetAtt: [WebSocketApi, Outputs.SocketApi]
        ConnectIntegration:
          Fn::GetAtt: [SocketIntegrations, Outputs.SocketApi]





