Parameters:
  SocketApi:
    Type: String
    Description: WebSocketApi string arn

  DefaultIntegration:
    Type: String
  ConnectIntegration:
    Type: String
    Description: Integration for the connect Route but I need an uri
  DisconnectIntegration:
    Type: String
  SendMessageIntegration:
    Type: String

  DefaultLambda:
    Type: String
  ConnectLambda:
    Type: String
    Description: Lambda for the connect Route but I need an uri
  DisconnectLambda:
    Type: String
  SendMessageLambda:
    Type: String




Resources:

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketApi
      RouteKey: $default
      Target: !Join
        - /
        - - integrations
          - !Ref     DefaultIntegration


  DefaultAPIInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DefaultLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${SocketApi}/beta/$default


  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref  ConnectIntegration

  ConnectAPIInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ConnectLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${SocketApi}/beta/$connect

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketApi
      RouteKey: $disconnect
      Target: !Join
        - /
        - - integrations
          - !Ref   DisconnectIntegration

  DisconnectAPIInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DisconnectLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${SocketApi}/beta/$disconnect


  SendMessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SocketApi
      RouteKey: sendmessage
      Target: !Join
        - /
        - - integrations
          - !Ref    SendMessageIntegration

  SendMessageAPIInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SendMessageLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${SocketApi}/beta/sendmessage


    
