Parameters:

  SocketApi:
    Type: String
    Description: WebSocketApi string arn

  ConnectLambda:
    Type: String
    Description: Lambda for the connect Route but I need an uri


Resources:


  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketApi
      #we need to change the connection type later.. not necessary for tests rn
      ConnectionType: INTERNET
      #ContentHandlingStrategy: String
      #CredentialsArn: String
      Description: ConnectRouteIntegration
      IntegrationMethod: POST #required by cloudformation
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref ConnectLambda

      PassthroughBehavior: String

Outputs:
  ConnectIntegration:
    Value: !Ref ConnectIntegration
