Parameters:

  SocketApi:
    Type: String
    Description: WebSocketApi string arn

  DefaultLambda:
    Type: String
  ConnectLambda:
    Type: String
    Description: Lambda for the connect Route but I need an uri
  DisconnectLambda:
    Type: String
  SendMessageLambda:
    Type: String


Resources:


  DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketApi
      #we need to change the connection type later.. not necessary for tests rn
      ConnectionType: INTERNET
      #ContentHandlingStrategy: String
      #CredentialsArn: String
      Description: DefaultRouteIntegration
      IntegrationMethod: POST #required by cloudformation
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultLambda}/invocations


  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketApi
      #we need to change the connection type later.. not necessary for tests rn
      ConnectionType: INTERNET
      #ContentHandlingStrategy: String
      #CredentialsArn: String
      Description: ConnectRouteIntegration
      IntegrationMethod: POST #required by cloudformation
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambda}/invocations



  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketApi
      #we need to change the connection type later.. not necessary for tests rn
      ConnectionType: INTERNET
      #ContentHandlingStrategy: String
      #CredentialsArn: String
      Description: DisconnectRouteIntegration
      IntegrationMethod: POST #required by cloudformation
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref DisconnectLambda



  SendMessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SocketApi
      #we need to change the connection type later.. not necessary for tests rn
      ConnectionType: INTERNET
      #ContentHandlingStrategy: String
      #CredentialsArn: String
      Description: SendMessageRouteIntegration
      IntegrationMethod: POST #required by cloudformation
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref SendMessageLambda

Outputs:
  ConnectIntegration:
    Value: !Ref ConnectIntegration

  DisconnectIntegration:
    Value: !Ref DisconnectIntegration

  DefaultIntegration:
    Value: !Ref DefaultIntegration

  SendMessageIntegration:
    Value: !Ref SendMessageIntegration
