Resources:

  MainGateWay:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      #ApiKeySelectionExpression: String
      Description: kuik api test
      #enabled for test
      DisableExecuteApiEndpoint: true
      DisableSchemaValidation: false
      FailOnWarnings: false
      IpAddressType: ipv4
      Name: websocket-chat
      ProtocolType: WEBSOCKET
      RouteKey: String
      RouteSelectionExpression: request.body.action
      #Tags: 
      #  Key: Value
      Version: 1

Outputs:
  MainGateWay:
    !Ref MainGateWay


