Resources:

  MainGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      #ApiKeySelectionExpression: String
      Description: kuik api test
      #enabled for test
      #DisableExecuteApiEndpoint: true
      #DisableSchemaValidation: false
      IpAddressType: ipv4
      Name: websocket-chat
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      #Tags: 
      #  Key: Value
      Version: 1

Outputs:
  SocketApi:
    Value: !Ref MainGateway


